ALTER TABLE "MapBoard" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "MapBoard" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "MapLocationPin" ALTER COLUMN "regionId" DROP NOT NULL;
ALTER TABLE "MapLocationPin" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
