import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router';
import { api } from '../lib/api.js';

const targetKinds = ['entity', 'field', 'objective', 'location_connection', 'monster_stat', 'monster_movement', 'monster_attack', 'monster_ability', 'monster_skill', 'monster_trait'];

export function DiscoveriesPage() {
  const { campaignId } = useParams();
  const queryClient = useQueryClient();
  const [grant, setGrant] = useState({ subjectType: 'user', subjectId: '', entityType: 'npc', entityId: '', targetKind: 'entity', targetKey: 'existence', allowance: 'allow' });
  const grants = useQuery({ queryKey: ['discoveries', campaignId], queryFn: () => api(`/api/v1/campaigns/${campaignId}/discoveries`) });
  const save = useMutation({ mutationFn: () => api(`/api/v1/campaigns/${campaignId}/discoveries`, { method: 'PUT', body: grant }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['discoveries', campaignId] }) });
  return <><div className="page-heading"><div><h1>Descobertas</h1><p>Allow/deny por usuário ou grupo, sem enviar segredos ao navegador.</p></div></div><div className="card form-grid discoveries-form"><label>Sujeito<select value={grant.subjectType} onChange={(e) => setGrant({ ...grant, subjectType: e.target.value })}><option value="user">Usuário</option><option value="group">Grupo</option></select></label><label>Subject ID<input value={grant.subjectId} onChange={(e) => setGrant({ ...grant, subjectId: e.target.value })} /></label><label>Entidade<select value={grant.entityType} onChange={(e) => setGrant({ ...grant, entityType: e.target.value })}>{['npc','location','item','monster','quest'].map((type) => <option key={type}>{type}</option>)}</select></label><label>Entity ID<input value={grant.entityId} onChange={(e) => setGrant({ ...grant, entityId: e.target.value })} /></label><label>Alvo<select value={grant.targetKind} onChange={(e) => setGrant({ ...grant, targetKind: e.target.value, targetKey: e.target.value === 'entity' ? 'existence' : grant.targetKey })}>{targetKinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>Target key<input value={grant.targetKey} onChange={(e) => setGrant({ ...grant, targetKey: e.target.value })} /></label><label>Regra<select value={grant.allowance} onChange={(e) => setGrant({ ...grant, allowance: e.target.value })}><option value="allow">allow ✓</option><option value="deny">deny ×</option></select></label><button className="primary" onClick={() => save.mutate()}>Aplicar descoberta</button>{save.error && <div className="alert error">{save.error.message}</div>}</div><div className="table-wrap"><table><thead><tr><th>Sujeito</th><th>Entidade</th><th>Alvo</th><th>Regra</th><th>Atualizado</th></tr></thead><tbody>{grants.data?.map((item) => <tr key={item.id}><td>{item.subjectType}:{item.subjectId}</td><td>{item.entityType}:{item.entityDomainId}</td><td>{item.targetKind}:{item.targetKey}</td><td><span className={`grant ${item.allowance}`}>{item.allowance === 'allow' ? '✓ allow' : '× deny'}</span></td><td>{new Date(item.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div></>;
}
